services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      LANG: ko_KR.UTF8
      LC_COLLATE: C
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
      POSTGRES_INITDB_ARGS: --data-checksums
    ports:
      - '5432:5432'
    restart: on-failure
    shm_size: 256MB
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql/root.crt:/var/lib/postgresql/root.crt
      - ./postgresql/server.crt:/var/lib/postgresql/server.crt
      - ./postgresql/server.key:/var/lib/postgresql/server.key
      - ./postgresql/pg_hba.conf:/var/lib/postgresql/pg_hba.conf
    command: >
      -c ssl=on
      -c ssl_ca_file=/var/lib/postgresql/root.crt
      -c ssl_cert_file=/var/lib/postgresql/server.crt
      -c ssl_key_file=/var/lib/postgresql/server.key
      -c hba_file=/var/lib/postgresql/pg_hba.conf

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6379:6379'
    restart: on-failure
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
