name: Docker Publish Backend

on:
  push:
    branches:
      - 'main'
      - 'release/**'
    paths:
      - '.github/workflows/docker-publish-backend.yml'
      - 'backend/**'
  pull_request:
    branches:
      - 'main'
      - 'release/**'
    paths:
      - '.github/workflows/docker-publish-backend.yml'
      - 'backend/**'

env:
  GCP_PROJECT_ID: bike-428810
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.5.0
        with:
          cosign-release: 'v2.2.4'

      # To build multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta-backend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/backend
          tags: |
            type=ref,event=branch
            type=sha,format=long

      - name: Build and push Docker image
        id: build-and-push-backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.meta-backend.outputs.tags }}
            ${{ secrets.DOCKERHUB_USERNAME }}/bike:backend-main
          labels: ${{ steps.meta-backend.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.meta-backend.outputs.tags }}
          DIGEST: ${{ steps.build-and-push-backend.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

      - uses: google-github-actions/auth@v2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          workload_identity_provider: projects/761490712850/locations/global/workloadIdentityPools/github/providers/my-repo

      - name: Deploy to Google Cloud Run
        if: ${{ github.event_name != 'pull_request' }}
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          image: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/bike:backend-main
          region: asia-northeast3
          project_id: ${{ env.GCP_PROJECT_ID }}
          service: bike-prod
